build_from:
  aarch64: "calimeroproject/knxserver:latest"
  amd64: "calimeroproject/knxserver:latest"
  armhf: "calimeroproject/knxserver:latest"
  armv7: "calimeroproject/knxserver:latest"
  i386: "calimeroproject/knxserver:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Calimero daemon"
  org.opencontainers.image.description: "Home Assistant Add-on: Calimero daemon"
